### ISSUE TITLE
Documentation around strict mode

### ISSUE THREAD

**Issue by Dfenniak** [awslabs/amazon-qldb-ledger-load-java#1]
Hey Dan 👋,

Loving the library so far. I was wondering if it would be worth it to document strict mode and maybe some of the other configuration options in the cloud formation files.

**Comment by Dfenniak** [comment]
I should note I mean in the README. It's well documented in the code.

**Comment by aws-dbblaner** [comment]
Will do!

**Comment by aws-dbblaner** [comment]
Add a Configuration section to the README to document some of the more obscure configuration parameters.
